import Pokedex, { Pokemon } from "pokedex-promise-v2";

const P = new Pokedex();

const SIGNATURES = new Set([
  "volt-tackle",
  "pika-papow",
  "zippy-zap",
  "splishy-splash",
  "floaty-fall",
  "veevee-volley",
  "sizzly-slide",
  "buzzy-buzz",
  "bouncy-bubble",
  "glitzy-glow",
  "baddy-bad",
  "sappy-seed",
  "freezy-frost",
  "sparkly-swirl",
  "kinesis",
  "shell-side-arm",
  "chloroblast",
  "barrage",
  "bone-club",
  "bonemerang",
  "shadow-bone",
  "mach-punch",
  "conversion",
  "conversion-2",
"infernal-parade",
"toxic-thread",
"eerie-spell",
"barb-barrage",
"present",
"psyshield-bash",
"twin-beam",
"triple-kick",
"eruption",
"heal-order",
"defend-order",
"attack-order",
"flower-shield",
"chatter",
"ceaseless-edge",
"simple-beam",
"secret-power",
"storm-throw",
"crafty-shield",
"gear-grind",
"snap-trap",
"esper-wing",
"fire-lash",
"fiery-dance",
"parting-shot",
"arm-thrust",
"kings-shield",
"topsy-turvy",
"electrify",
"fairy-lock",
"forests-curse",
"trick-or-treat",
"spirit-shackle",
"triple-arrows",
"sparkling-aria",
"beak-blast",
"ice-hammer",
"revelation-dance",
"pollen-puff",
"accelerock",
"baneful-bunker",
"solar-blade",
"trop-kick",
"floral-healing",
"instruct",
"shore-up",
"purify",
"shell-trap",
"anchor-shot",
"clanging-scales",
"clangorous-soul",
"drum-beating",
"pyro-ball",
"court-change",
"snipe-shot",
"tar-shot",
"grav-apple",
"apple-acid",
"overdrive",
"octolock",
"teatime",
"magic-powder",
"confide",
"false-surrender",
"spirit-break",
"obstruct",
"meteor-assault",
"decorate",
"no-retreat",
"aura-wheel",
"bolt-break",
"fishious-rend",
"dragon-darts",
"water-shuriken",
"stone-axe",
"flower-trick",
"torch-song",
"aqua-step",
"silk-trap",
"population-bomb",
"armor-cannon",
"bitter-blade",
"doodle",
"spicy-extract",
"lumina-crash",
"gigaton-hammer",
"triple-dive",
"jet-punch",
"spin-out",
"mortal-spin",
"fillet-away",
"order-up",
"rage-fist",
"kowtow-cleave",
"glaive-rush",
"make-it-rain",
"syrup-bomb",
"fickle-beam",
]);

const LEGENDARYSIGNATURES= new Set([
  "freezing-glare",
"thunderous-kick",
"fiery-wrath",
"psystrike",
"aeroblast",
"heal-bell",
"mist-ball",
"luster-purge",
"origin-pulse",
"precipice-blades",
"dragon-ascent",
"doom-desire",
"roar-of-time",
"spatial-rend",
"shadow-force",
"magma-storm",
"crush-grip",
"lunar-dance",
"lunar-blessing",
"dark-void",
"seed-flare",
"judgement",
"searing-shot",
"v-create",
"fusion-flare",
"blue-flare",
"fusion-bolt",
"bolt-strike",
"glaciate",
"ice-burn",
"freeze-shock",
"secret-sword",
"relic-song",
"techno-blast",
"light-of-ruin",
"geomancy",
"oblivion-wing",
"lands-wrath",
"thousand-arrows",
"thousand-waves",
"core-enforcer",
"diamond-storm",
"hyperspace-hole",
"hyperspace-fury",
"steam-eruption",
"multi-attack",
"sunsteel-strike",
"moongeist-beam",
"prismatic-laser",
"photon-geyser",
"fleur-cannon",
"spectral-thief",
"mind-blown",
"plasma-fists",
"double-iron-bash",
"behemoth-blade",
"behemoth-bash",
"dynamax-cannon",
"eternabeam",
"wicked-blow",
"surging-strikes",
"jungle-healing",
"thunder-cage",
"dragon-energy",
"glacial-lance",
"astral-barrage",
"ruination",
"collision-course",
"electro-drift",
"hydro-steam",
"psyblade",
"burning-bulwark",
"thunderclap",
"rising-voltage",
"mighty-cleave",
"tachyon-cutter",
"tera-starstorm",
"malignant-chain"
])
const BANNED = new Set([
    "sketch"
])

const zmoves = new Set([]);

export async function getRandLearnableMove(pokemon: Pokemon){
    let random = Math.floor(Math.random() * pokemon.moves.length);
    return await P.getMoveByName(pokemon.moves[random]!.move.name);
}



export async function getRandMove(){
    const moves = await P.getResource("https://pokeapi.co/api/v2/move/?offset=0&limit=-1");
    let random = Math.floor(Math.random() * moves.results.length);
    P.getMoveByName(moves.results[random]);
}


export function isSignatureMove(){

}

export function isZMove(){

}

export function isGMax(name: string){
    return name.startsWith("g-max")
}